### ISSUE TITLE
You can no longer connect to Ysagoon

### ISSUE THREAD

**Issue by seasquirt** [Globulation2/glob2#113]
maybe implement another way to play online?

**Comment by progval** [comment]
It was stuck in an infinite loop in `NetConnection::~NetConnection`:

```
       │    while(!connect.hasThreadExited());
  1.11 │63:   mov   -0x38(%rbp),%rax
  0.48 │      mov   %rax,%rdi
  0.00 │    → call  NetConnectionThread::hasThreadExited
  0.06 │      xor   $0x1,%eax
  0.06 │      test  %al,%al
 98.28 │    ↓ je    78
  0.01 │    ↑ jmp   63
```

backtrace:

```
#0  0x000055c40205afd6 in NetConnectionThread::hasThreadExited (this=0x55c4023f9b50) at src/NetConnectionThread.cpp:271
#1  0x000055c40204f167 in NetConnection::~NetConnection (this=0x55c4023f9b50, __in_chrg=<optimized out>) at src/NetConnection.cpp:55
#2  0x000055c4021057e3 in boost::checked_delete<NetConnection> (x=0x55c4023f9b50) at /usr/include/boost/core/checked_delete.hpp:36
#3  0x000055c402106648 in boost::detail::sp_counted_impl_p<NetConnection>::dispose (this=0x55c4024a5cf0) at /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:89
#4  0x000055c40204abed in boost::detail::sp_counted_base::release (this=0x55c4024a5cf0) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:120
#5  0x000055c40204ac79 in boost::detail::shared_count::~shared_count (this=0x55c40241f698, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/detail/shared_count.hpp:432
#6  0x000055c4020ca392 in boost::shared_ptr<NetConnection>::~shared_ptr (this=0x55c40241f690, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:335
#7  0x000055c4021050bc in YOGServerPlayer::~YOGServerPlayer (this=0x55c40241f680, __in_chrg=<optimized out>) at src/YOGServerPlayer.h:38
#8  0x000055c4021050dd in boost::checked_delete<YOGServerPlayer> (x=0x55c40241f680) at /usr/include/boost/core/checked_delete.hpp:36
#9  0x000055c4021066f8 in boost::detail::sp_counted_impl_p<YOGServerPlayer>::dispose (this=0x55c4024a3420) at /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:89
#10 0x000055c40204abed in boost::detail::sp_counted_base::release (this=0x55c4024a3420) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:120
#11 0x000055c40204ac79 in boost::detail::shared_count::~shared_count (this=0x55c4023f9930, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/detail/shared_count.hpp:432
#12 0x000055c4020cc79e in boost::shared_ptr<YOGServerPlayer>::~shared_ptr (this=0x55c4023f9928, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:335
```

It was running on an old commit (33bda73df730d02fe50e42fa329081351e9b0a00) so I'm going to rebuild it before restarting.

**Comment by stephanemagnenat** [comment]
Thank you for checking!

**Comment by progval** [comment]
The server is back up now. For some reason my client segfaults when connecting to the server, but it has been doing this for a while.

**Comment by progval** [comment]
The serve keeps getting stuck. On the latest master (52d9e523d05be58611433ea4a665df7f2550598a):

```
#0  NetConnectionThread::hasThreadExited (this=0x555f46570ce0) at src/NetConnectionThread.cpp:274
#1  0x0000555f459b487c in NetConnection::~NetConnection (this=0x555f46570ce0, __in_chrg=<optimized out>) at src/NetConnection.cpp:57
#2  0x0000555f45a6c61d in boost::checked_delete<NetConnection> (x=0x555f46570ce0) at /usr/include/boost/core/checked_delete.hpp:36
#3  0x0000555f45a6d750 in boost::detail::sp_counted_impl_p<NetConnection>::dispose (this=0x555f46577260) at /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:89
#4  0x0000555f459b012d in boost::detail::sp_counted_base::release (this=0x555f46577260) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:120
#5  0x0000555f459b01b9 in boost::detail::shared_count::~shared_count (this=0x555f46578238, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/detail/shared_count.hpp:432
#6  0x0000555f45a30d34 in boost::shared_ptr<NetConnection>::~shared_ptr (this=0x555f46578230, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:335
#7  0x0000555f45a942e6 in std::__new_allocator<boost::shared_ptr<NetConnection> >::destroy<boost::shared_ptr<NetConnection> > (this=0x7fffd478afe8, __p=0x555f46578230) at /usr/include/c++/12/bits/new_allocator.h:181
#8  0x0000555f45a9419e in std::allocator_traits<std::allocator<boost::shared_ptr<NetConnection> > >::destroy<boost::shared_ptr<NetConnection> > (__a=..., __p=0x555f46578230) at /usr/include/c++/12/bits/alloc_traits.h:535
#9  0x0000555f45a93fe1 in std::vector<boost::shared_ptr<NetConnection>, std::allocator<boost::shared_ptr<NetConnection> > >::_M_erase (this=0x7fffd478afe8, __position=...) at /usr/include/c++/12/bits/vector.tcc:181
#10 0x0000555f45a93b58 in std::vector<boost::shared_ptr<NetConnection>, std::allocator<boost::shared_ptr<NetConnection> > >::erase (this=0x7fffd478afe8, __position=...) at /usr/include/c++/12/bits/stl_vector.h:1530
#11 0x0000555f45a93647 in YOGServerRouterManager::update (this=0x7fffd478afe8) at src/YOGServerRouterManager.cpp:74
#12 0x0000555f45a679bc in YOGServer::update (this=0x7fffd478ad90) at src/YOGServer.cpp:117
#13 0x0000555f45a67b37 in YOGServer::run (this=0x7fffd478ad90) at src/YOGServer.cpp:157
#14 0x0000555f45a30be0 in Glob2::run (this=0x7fffd478b1cf, argc=1, argv=0x7fffd478b2e8) at src/Glob2.cpp:233
#15 0x0000555f45a30c8d in main (argc=1, argv=0x7fffd478b2e8) at src/Glob2.cpp:441
```
